import os, json, math, time
import dotenv
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    EarlyStoppingCallback,
    AutoModelForSeq2SeqLM,
)
import torch
import numpy as np
import random
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import jsonlines

dotenv.load_dotenv('.env')
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

# %% [markdown]
# ## Load Dataset WMT17
# 
# Device space limitation.

# %%
SUPPORTED_LANGS = ['zh-en'] #'cs-en', 'de-en', 'fi-en', 'lv-en', 'ru-en', 'tr-en', ]
lang_map = {
        'en': 'en_XX',
        'zh': 'zh_CN',
        'cs': 'cs_CZ',
        'de': 'de_DE',
        'fi': 'fi_FI',
        'lv': 'lv_LV',
        'ru': 'ru_RU',
        'tr': 'tr_TR',
    }
model_map = {
    'mbart': 'facebook/mbart-large-50-many-to-many-mmt',
    'opus-mt': 'Helsinki-NLP/opus-mt-zh-en',
    'nllb': 'facebook/nllb-200-distilled-600M',
}
# Set the best model parameters here!
model_params = {
    'mbart': {'num_train': 2048},
    'opus-mt': {'num_train': 2048},
    'nllb': {'num_train': 2048},
}

# %% [markdown]
# ## Load Pretrained Model.
# 
# | Model key | HF model id                              | # Params | Arch.                     | Languages             | Pre-train data        | Tokeniser           | Requires prompt prefix?    | Size on disk |
# | --------- | ---------------------------------------- | -------- | ------------------------- | --------------------- | --------------------- | ------------------- | -------------------------- | ------------ |
# | mbart     | facebook/mbart-large-50-many-to-many-mmt | 610 M    | Transformer-large (12-12) | 50 langs, any→any     | CC25 + mined data     | SentencePiece 250 k | No (src/tgt codes in call) | ~2.3 GB      |
# | opus-mt   | Helsinki-NLP/opus-mt-zh-en               | 74 M     | Transformer-base (6-6)    | zh → en only          | OPUS corpus           | SentencePiece 32 k  | No                         | ~298 MB      |
# | nllb      | facebook/nllb-200-distilled-600M         | 1.3 B    | Transformer (12-12, MoE)  | 200 langs, any→any    | NLLB-200 corpus       | SentencePiece 256 k | No                         | ~5 GB        |
#

# %%
def build_model(model_name, src_lang, tgt_lang):
    model_name = model_map[model_name]
    tok = AutoTokenizer.from_pretrained(model_name, src_lang=src_lang, tgt_lang=tgt_lang, cache_dir='./cache')
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name, cache_dir='./cache')
    return tok, model


# %%
import random
import os
import numpy as np
import torch

def seed_all(seed: int = 42):
    # 1. Python builtin
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

    # 2. NumPy
    np.random.seed(seed)

    # 3. PyTorch
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    print(f"[seed_all] Global random seed set to {seed}")

# %% [markdown]
# ## Load MT Metrics

# %%
from evaluate import load

bleu = load("sacrebleu", cache_dir='./cache')
chrf = load("chrf", cache_dir='./cache')


# %% [markdown]
# ## Preprocess Datasets

# %%
def split_train_test(full_train, num_trains, num_test, num_val):
    indices = random.sample(range(len(full_train)), num_trains + num_test + num_val)
    raw_train = full_train.select(indices[:num_trains])
    raw_test = full_train.select(indices[num_trains:num_trains + num_test])
    raw_val = full_train.select(indices[num_trains + num_test:])
    return raw_train, raw_test, raw_val


# %%
def flip_dataset(raw, src, tgt):
    def flip(batch):
        batch["translation"] = {src: batch["translation"][tgt],
                                tgt: batch["translation"][src]}
        return batch
    return raw.map(flip, batched=False)


# %%
def clean_memory():
    import torch, gc
    if torch.cuda.is_available():
        torch.cuda.empty_cache()  # 把未用缓存还给 CUDA
    elif torch.backends.mps.is_available():
        torch.mps.empty_cache()   # 把未用缓存还给 CUDA
    gc.collect()               # 再让 Python 回收一次

# %%
def train_model(model_name: str, src: str, tgt: str, num_train=10, num_test=10, num_val=10):
    need_prompt = model_name.startswith('t5')
    data = load_dataset("wmt17", name="-".join([src, tgt]), split="train", cache_dir='./cache')

    lang_src = lang_map[src]
    lang_tgt = lang_map[tgt]
    tok, model = build_model(model_name, lang_src, lang_tgt)

    num_train_epochs = 10
    max_src, max_tgt = 128, 128

    def compute_metrics(eval_preds):
        preds, labels = eval_preds

        # --- FIX: Prevent OverflowError during decoding ---
        # The OverflowError happens when token IDs in 'preds' are extremely large 
        # (e.g., garbage values generated by an unstable model) and exceed the 
        # integer capacity of the fast tokenizer's decode function.
        
        # 1. Ensure preds is a numpy array and get vocabulary size
        if hasattr(preds, 'cpu'):
             # Convert tensor to numpy array if it hasn't been already
             preds = preds.cpu().numpy()
             
        max_valid_id = len(tok)
        
        # 2. Identify tokens that are out of the valid range [0, max_valid_id - 1]
        # and replace them with the pad token ID.
        # This cleans up large/negative invalid IDs before the fast tokenizer attempts conversion.
        preds = np.where((preds >= max_valid_id) | (preds < 0), tok.pad_token_id, preds)
        
        # --- Original Labels cleaning (required for Seq2Seq) ---
        labels = np.where(labels != -100, labels, tok.pad_token_id)
        
        # Decoding now happens with safe token IDs
        pred_str = tok.batch_decode(preds, skip_special_tokens=True)
        label_str = tok.batch_decode(labels, skip_special_tokens=True)

        bleu_score  = bleu.compute(predictions=pred_str,
                                     references=[[r] for r in label_str])["score"]
        chrf_score  = chrf.compute(predictions=pred_str,
                                     references=label_str)["score"]

        return {"bleu": bleu_score, "chrf": chrf_score}

    def encode(ex):
        # Using clearer variable names: src_text (Chinese) and tgt_text (English)
        src_text = [item[src] for item in ex["translation"]] # Source (Chinese)
        tgt_text = [item[tgt] for item in ex["translation"]] # Target (English)
        
        if need_prompt:
            # FIX 1: T5 requires the prompt to be prepended to the SOURCE text (Encoder Input).
            # The label (text_target) should remain the clean target text.
            src_text = [f"translate Chinese to English: " + item for item in src_text]

        # Tokenize the prompted source text and the clean target text (labels)
        model_inputs = tok(
            src_text,
            text_target=tgt_text,
            max_length=max_src,
            truncation=True,
            padding=False,          # 动态 padding，由 data_collator 完成
        )
        return model_inputs

    raw_train, raw_test, raw_val = split_train_test(data,
                                                    num_trains=num_train, num_test=num_test, num_val=num_val)
    # Why we tokenize the split instead of data? Since data is very large, and we only use a small part of it!!
    # So 3 times tokenizations is OK.
    tokenised_train = raw_train.map(encode, batched=True)
    tokenised_val = raw_val.map(encode, batched=True)
    tokenised_test = raw_test.map(encode, batched=True)

    data_coll = DataCollatorForSeq2Seq(tok, model=model)

    args = Seq2SeqTrainingArguments(
        # output_dir='/content/output',
        eval_strategy="steps",
        eval_steps=500,
        logging_steps=100,
        save_steps=500,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=4,
        gradient_accumulation_steps=4,
        learning_rate=3e-5,
        num_train_epochs=num_train_epochs,
        predict_with_generate=True,
        generation_max_length=max_tgt,
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="bleu",
        greater_is_better=True,
        report_to="none",
        fp16=True,
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=args,
        train_dataset=tokenised_train,
        eval_dataset=tokenised_val,
        processing_class=tok,
        data_collator=data_coll,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
    )
    # trainer.train()
    return model, tok


# %% [markdown]
# ## Run Inference

# %% [markdown]
# Obtain the input setences.

# %%
dataset = load_dataset('wmt17', 'zh-en', split='test', cache_dir='./cache')

# %%
seed_all(111) # Set a seed to 111.

# %%
len(dataset)

# %%
num_inputs = 5 # Fixed to 5.

input_data = dataset.select(random.choices(range(len(dataset)), k=num_inputs))
len(input_data)

# %%
input_data

# %%
def get_avail_device():
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
    return device

# %%
import torch
from tqdm.auto import tqdm

def translate(model, tok, input_data, need_prompt=True):
    model.eval()
    device = get_avail_device()

    # 1. 生成参数（可按需调）
    gen_kwargs = {
        "max_length": 64,
        "num_beams": 4,
        "early_stopping": True,
    }

    out_f = []

    for sample in tqdm(input_data, desc="Translating"):
        raw_src_text = sample["translation"][src]
        
        if need_prompt:
            # FIX 2: Prepend the T5 task prompt to the source sentence for inference.
            prompted_src_text = f"translate Chinese to English: {raw_src_text}"
            
        inputs = tok(prompted_src_text, return_tensors="pt").to(device)

        with torch.no_grad():
            pred = model.generate(**inputs, **gen_kwargs)

        hyp = tok.decode(pred[0], skip_special_tokens=True)
        out_f.append(hyp.strip())

    return out_f


# %% [markdown]
# Run each model.

# %%
tgt, src = 'en', 'zh'

translation_results = {'tgt': [sample['translation'][tgt] for sample in input_data],
                       'src': [sample['translation'][src] for sample in input_data]}

for key in model_map:
    num_train = 32 #model_params[key].get("num_train", 32)
    model, tok = train_model(key, src='zh', tgt='en', num_train=num_train, num_test=20)
    translation_results[key] = translate(model, tok, input_data)

# %%
df = pd.DataFrame(translation_results)
df.to_csv('./translation_results.csv', index=False)

# %% [markdown]
# ## Dimension Reduction & Clustering

# %%
df = pd.read_csv('./translate_result.csv')

# %%
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import umap
import matplotlib.pyplot as plt
import seaborn as sns

model_map = {
    'mbart': 'facebook/mbart-large-50-many-to-many-mmt',
    'opus-mt': 'Helsinki-NLP/opus-mt-zh-en',
    'nllb': 'facebook/nllb-200-distilled-600M',
}

# 假设你的 DataFrame 长这样：
# | tgt | pred_modelA | pred_modelB | pred_modelC | ...

# 1. 收集所有句子 + 标签
sentences, labels, markers = [], [], []   # markers: 'gt' 或模型名
for idx, row in df.iterrows():
    sentences.append(row["tgt"])
    labels.append(f"sample{idx}")
    markers.append("gt")          # ground-truth
    for model_name in model_map:
        if model_name in df.columns:
            sentences.append(row[model_name])
            labels.append(f"sample{idx}")
            markers.append(model_name)

# %%
# 2. TF-IDF 向量化
vectorizer = TfidfVectorizer(lowercase=True, stop_words=None, max_features=20_000)
X = vectorizer.fit_transform(sentences)   # shape: (n_sent, n_features)
fontsize = 10
S = 150

# 3. UMAP 降维
reducer = umap.UMAP(n_neighbors=5, min_dist=0.1, metric="cosine", random_state=42)
XY = reducer.fit_transform(X)             # shape: (n_sent, 2)

# 4. 画图
plt.figure(figsize=(8, 5))
unique_samples = sorted(set(labels))
palette = sns.color_palette("husl", n_colors=len(unique_samples))
color_map = {sam: palette[i] for i, sam in enumerate(unique_samples)}

for i, (x, y) in enumerate(XY):
    color = color_map[labels[i]]
    if markers[i] == "gt":        # 五角星
        plt.scatter(x, y, marker="*", s=S*2, c=[color], edgecolor="black")
    else:                         # 模型预测
        plt.scatter(x, y, c=[color], s=S, alpha=0.8)
        # 在点旁边写模型名（只写一次，防止重叠）
        plt.text(x, y, markers[i], fontsize=fontsize, ha="left")

# 图例：颜色 = 样本 ID
legend_elements = [plt.Line2D([0], [0], marker="o", color="w",
                              markerfacecolor=color_map[sam], markersize=8, label=sam)
                   for sam in unique_samples]
plt.legend(handles=legend_elements, title="Sample ID", bbox_to_anchor=(1.05, 1), fontsize=fontsize, loc="upper left")
plt.title("UMAP projection of TF-IDF vectors (GT (*) vs. model predictions)")
plt.tight_layout()
plt.grid(True)
plt.savefig('./cluster.jpg')

# %%
vectorizer.vocabulary_

# %%
df.head()

# %%
df.mbart